//
// Copyright (c) Clemens Cords (mail@clemens-cords.com), created 3/20/23
//

#pragma once

#include <gtk/gtk.h>

namespace mousetrap
{
    enum class RevealerTransitionType
    {
        NONE = GTK_REVEALER_TRANSITION_TYPE_NONE,
        CROSSFADE = GTK_REVEALER_TRANSITION_TYPE_CROSSFADE,

        SLIDE_RIGHT = GTK_REVEALER_TRANSITION_TYPE_SLIDE_RIGHT,
        SLIDE_LEFT = GTK_REVEALER_TRANSITION_TYPE_SLIDE_LEFT,
        SLIDE_DOWN = GTK_REVEALER_TRANSITION_TYPE_SLIDE_DOWN,
        SLIDE_UP = GTK_REVEALER_TRANSITION_TYPE_SLIDE_UP,

        SWING_RIGHT = GTK_REVEALER_TRANSITION_TYPE_SWING_RIGHT,
        SWING_LEFT = GTK_REVEALER_TRANSITION_TYPE_SWING_LEFT,
        SWING_DOWN = GTK_REVEALER_TRANSITION_TYPE_SWING_DOWN,
        SWING_UP = GTK_REVEALER_TRANSITION_TYPE_SWING_UP,
    };

    enum class StackTransitionType
    {
        NONE = GTK_STACK_TRANSITION_TYPE_NONE,
        CROSSFADE = GTK_STACK_TRANSITION_TYPE_CROSSFADE,

        SLIDE_RIGHT = GTK_STACK_TRANSITION_TYPE_SLIDE_RIGHT,
        SLIDE_LEFT = GTK_STACK_TRANSITION_TYPE_SLIDE_LEFT,
        SLIDE_DOWN = GTK_STACK_TRANSITION_TYPE_SLIDE_DOWN,
        SLIDE_UP = GTK_STACK_TRANSITION_TYPE_SLIDE_UP,
        SLIDE_LEFT_RIGHT = GTK_STACK_TRANSITION_TYPE_SLIDE_LEFT_RIGHT,
        SLIDE_UP_DOWN = GTK_STACK_TRANSITION_TYPE_SLIDE_UP_DOWN,

        OVER_UP = GTK_STACK_TRANSITION_TYPE_OVER_UP,
        OVER_DOWN = GTK_STACK_TRANSITION_TYPE_OVER_DOWN,
        OVER_LEFT = GTK_STACK_TRANSITION_TYPE_OVER_LEFT,
        OVER_RIGHT = GTK_STACK_TRANSITION_TYPE_OVER_RIGHT,

        UNDER_UP = GTK_STACK_TRANSITION_TYPE_UNDER_UP,
        UNDER_DOWN = GTK_STACK_TRANSITION_TYPE_UNDER_DOWN,
        UNDER_LEFT = GTK_STACK_TRANSITION_TYPE_UNDER_LEFT,
        UNDER_RIGHT = GTK_STACK_TRANSITION_TYPE_UNDER_RIGHT,

        OVER_UP_DOWN = GTK_STACK_TRANSITION_TYPE_OVER_UP_DOWN,
        OVER_DOWN_UP = GTK_STACK_TRANSITION_TYPE_OVER_DOWN_UP,
        OVER_LEFT_RIGHT = GTK_STACK_TRANSITION_TYPE_OVER_LEFT_RIGHT,
        OVER_RIGHT_LEFT = GTK_STACK_TRANSITION_TYPE_OVER_RIGHT_LEFT,

        ROTATE_LEFT = GTK_STACK_TRANSITION_TYPE_ROTATE_LEFT,
        ROTATE_RIGHT = GTK_STACK_TRANSITION_TYPE_ROTATE_RIGHT,
        ROTATE_LEFT_RIGHT = GTK_STACK_TRANSITION_TYPE_ROTATE_LEFT_RIGHT
    };
}